development:
  adapter: postgresql
  encoding: unicode
  database: DATABASE_URL
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: DATABASE_URL
  pool: 5
  username:
  password:
